### ISSUE TITLE
Game freezes 

### ISSUE THREAD

**Issue by Michaelj15** [CrusheerPL/FS22_thirdPersonView#1]
Game freezes after shutdown with the third person view enabled. Tested with multiple people.

**Comment by CrusheerPL** [comment]
Thanks for report. I was able to reproduce that issue - result:

> 2022-02-17 20:06 Error: Running LUA method 'update'.
> dataS/scripts/BaseMission.lua(1226) : attempt to index field 'hud' (a nil value)
> 2022-02-17 20:06 Error: Running LUA method 'draw'.
> dataS/scripts/BaseMission.lua(1326) : attempt to index field 'hud' (a nil value)
> 2022-02-17 20:06 Error: Running LUA method 'mouseEvent'.
> dataS/scripts/FSBaseMission.lua(1967) : attempt to index field 'hud' (a nil value)
> 2022-02-17 20:06 Error: Running LUA method 'mouseEvent'.
> dataS/scripts/FSBaseMission.lua(1967) : attempt to index field 'hud' (a nil value)

Tested with new savegame on Elmcreek. Errors occured only with TPV mod loaded:
[log w/ TPV mod only](https://github.com/CrusheerPL/FS22_thirdPersonView/files/8091503/log.txt)
[log without any mods](https://github.com/CrusheerPL/FS22_thirdPersonView/files/8091598/log.txt)

**Comment by Michaelj15** [comment]
> Thanks for report. I was able to reproduce that issue - result:
> 
> > 2022-02-17 20:06 Error: Running LUA method 'update'.
> > dataS/scripts/BaseMission.lua(1226) : attempt to index field 'hud' (a nil value)
> > 2022-02-17 20:06 Error: Running LUA method 'draw'.
> > dataS/scripts/BaseMission.lua(1326) : attempt to index field 'hud' (a nil value)
> > 2022-02-17 20:06 Error: Running LUA method 'mouseEvent'.
> > dataS/scripts/FSBaseMission.lua(1967) : attempt to index field 'hud' (a nil value)
> > 2022-02-17 20:06 Error: Running LUA method 'mouseEvent'.
> > dataS/scripts/FSBaseMission.lua(1967) : attempt to index field 'hud' (a nil value)
> 
> Tested with new savegame on Elmcreek. Errors occured only with TPV mod loaded: [log w/ TPV mod only](https://github.com/CrusheerPL/FS22_thirdPersonView/files/8091503/log.txt) [log without any mods](https://github.com/CrusheerPL/FS22_thirdPersonView/files/8091598/log.txt)

No problem. I didn't know how to trace the problem otherwise I would have done this for you ;) The only thing I see, is with only the 3rd person mod on, the screen turns black after quiting the game. So the main beginscreen of the game don't load again. However, despite this problem, I will continue to use the mod, because it's just great 😃
